package com.example;

public enum EventType {
    ORDER_CREATED,
    ORDER_REJECTED,
    ORDER_CONFIRMED,
    ORDER_ITEM_RESERVED,
    ORDER_ITEM_OUT_OF_STOCK,
    ORDER_PAID,
    ORDER_PAYMENT_FAILURE,
}
