---
micronaut:
  application:
    name: inventory-service
  server:
    port: 8083
---
kafka:
  bootstrap:
    servers: localhost:9092

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: com.example.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update

